export PYTHONPATH=./

# CUDAVISIBLE_DEVICES=0 python nerfstudio-gaussian_splatting/nerfstudio/scripts/gaussian_splatting/run_viewer.py --model-path /DATA_EDS2/yangry/experiments/mipnerf360/graph_10_no_all/bicycle --config.pipeline.model.nn-com-path /DATA_EDS2/yangry/experiments/mipnerf360/graph_10_no_all/bicycle --config.viewer.websocket-port 7001 
# CUDAVISIBLE_DEVICES=0 python nerfstudio-gaussian_splatting/nerfstudio/scripts/gaussian_splatting/run_viewer.py --model-path /DATA_EDS2/yangry/experiments/mipnerf360/graph_10_no_all/bonsai --config.pipeline.model.nn-com-path /DATA_EDS2/yangry/experiments/mipnerf360/graph_10_no_all/bonsai --config.viewer.websocket-port 7002 
CUDAVISIBLE_DEVICES=1 python nerfstudio-gaussian_splatting/nerfstudio/scripts/gaussian_splatting/run_viewer.py --model-path /DATA_EDS2/yangry/experiments/mipnerf360/graph_10_no_all/counter --config.pipeline.model.nn-com-path /DATA_EDS2/yangry/experiments/mipnerf360/graph_10_no_all/counter --config.viewer.websocket-port 7003 
CUDAVISIBLE_DEVICES=1 python nerfstudio-gaussian_splatting/nerfstudio/scripts/gaussian_splatting/run_viewer.py --model-path /DATA_EDS2/yangry/experiments/mipnerf360/graph_10_no_all/garden --config.pipeline.model.nn-com-path /DATA_EDS2/yangry/experiments/mipnerf360/graph_10_no_all/garden --config.viewer.websocket-port 7004 
CUDAVISIBLE_DEVICES=2 python nerfstudio-gaussian_splatting/nerfstudio/scripts/gaussian_splatting/run_viewer.py --model-path /DATA_EDS2/yangry/experiments/mipnerf360/graph_10_no_all/room --config.pipeline.model.nn-com-path /DATA_EDS2/yangry/experiments/mipnerf360/graph_10_no_all/room --config.viewer.websocket-port 7005 
CUDAVISIBLE_DEVICES=2 python nerfstudio-gaussian_splatting/nerfstudio/scripts/gaussian_splatting/run_viewer.py --model-path /DATA_EDS2/yangry/experiments/mipnerf360/graph_10_no_all/kitchen --config.pipeline.model.nn-com-path /DATA_EDS2/yangry/experiments/mipnerf360/graph_10_no_all/kitchen --config.viewer.websocket-port 7006 
CUDAVISIBLE_DEVICES=2 python nerfstudio-gaussian_splatting/nerfstudio/scripts/gaussian_splatting/run_viewer.py --model-path /DATA_EDS2/yangry/experiments/mipnerf360/graph_10_no_all/stump --config.pipeline.model.nn-com-path /DATA_EDS2/yangry/experiments/mipnerf360/graph_10_no_all/stump --config.viewer.websocket-port 7007 

# CUDAVISIBLE_DEVICES=2 python nerfstudio-gaussian_splatting/nerfstudio/scripts/gaussian_splatting/run_viewer.py --model-path /DATA_EDS2/yangry/experiments/mipnerf360/graph_10_no_all/stump --config.pipeline.model.nn-com-path /DATA_EDS2/yangry/experiments/mipnerf360/graph_10_no_all/stump --config.viewer.websocket-port 7007 
# CUDAVISIBLE_DEVICES=2 python nerfstudio-gaussian_splatting/nerfstudio/scripts/gaussian_splatting/run_viewer.py --model-path /DATA_EDS2/yangry/experiments/mipnerf360/graph_10_no_all/stump --config.pipeline.model.nn-com-path /DATA_EDS2/yangry/experiments/mipnerf360/graph_10_no_all/stump --config.viewer.websocket-port 7007 

# CUDAVISIBLE_DEVICES=2 python nerfstudio-gaussian_splatting/nerfstudio/scripts/gaussian_splatting/run_viewer.py --model-path /DATA_EDS2/yangry/experiments/mipnerf360/graph_10_no_all/stump --config.pipeline.model.nn-com-path /DATA_EDS2/yangry/experiments/mipnerf360/graph_10_no_all/stump --config.viewer.websocket-port 7007 
# CUDAVISIBLE_DEVICES=2 python nerfstudio-gaussian_splatting/nerfstudio/scripts/gaussian_splatting/run_viewer.py --model-path /DATA_EDS2/yangry/experiments/mipnerf360/graph_10_no_all/stump --config.pipeline.model.nn-com-path /DATA_EDS2/yangry/experiments/mipnerf360/graph_10_no_all/stump --config.viewer.websocket-port 7007 

wait